name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  publish:
    uses: sebnozzi/minimicro-actions/.github/workflows/itch-deploy.yaml@feature/webgl-1.2-p2
    with:
      minidisk_main_file: demo.ms
      minidisk_additional_entries: >-
        morning-mood-autumn-morning-g830d5e964_1280.jpg
        window-gaf5aae649_1280.png
        fogmask.png
      custom_executable_name: FoggyWindow
      itch_io_username: sebnozzi
      itch_io_game_id: foggy-window
    secrets:
      itch_io_api_key: ${{ secrets.ITCH_IO_API_KEY }}
